# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Prayer Times"
  org.opencontainers.image.description: "Islamic Prayer Times fetched from Diyanet"
  org.opencontainers.image.source: "https://github.com/besanur/homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
